[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
async-channel = "2.5.0"
dirs = "6.0.0"
enigo = { version = "0.6.1", features = ["serde", "wayland"] }
rand = "0.10.2"
serde = "1.0.229"
serde_json = "1.0.151"
strum = "0.28.0"
tokio = "1.53.1"

wayclick_frontend = { path = "crates/frontend/" }
wayclick_schema = { path = "crates/schema/" }
