[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.1"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
dirs = "6.0.0"
rand = "0.10.2"
serde = "1.0.229"
serde_json = "1.0.151"
strum = "0.28.0"
strum_macros = "0.28.0"
tokio = { version = "1.53.1", features = ["full"] }

wayclick_click = { path = "crates/click/" }
wayclick_frontend = { path = "crates/frontend/" }
wayclick_schema = { path = "crates/schema/" }
