[package]
name = "wayclick_frontend"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
dirs.workspace = true
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
gpui-component-assets = {
  git = "https://github.com/longbridge/gpui-component.git"
}
gpui_platform = {
  git = "https://github.com/zed-industries/zed",
  features = ["font-kit", "runtime_shaders", "wayland"]
}
rand.workspace = true
rust-embed = "8.12.0"
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tokio.workspace = true

wayclick_schema.workspace = true
